# Generated by Django 6.0.2 on 2026-02-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingitem',
            options={'ordering': ['-is_pinned', 'order', 'created_at']},
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
